// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ArchiveGoal(arg1:string):Promise<void>;

export function ArchiveInitiative(arg1:string):Promise<void>;

export function ArchiveKPI(arg1:string):Promise<void>;

export function CompareSnapshots(arg1:string,arg2:string):Promise<Array<main.KPIComparisonOutput>>;

export function CreateGoal(arg1:main.CreateGoalInput):Promise<main.GoalOutput>;

export function CreateInitiative(arg1:main.CreateInitiativeInput):Promise<main.InitiativeOutput>;

export function CreateKPI(arg1:main.CreateKPIInput):Promise<main.KPIOutput>;

export function CreateSnapshot(arg1:string):Promise<main.SnapshotOutput>;

export function DeleteKPI(arg1:string):Promise<void>;

export function DeleteKPIEntry(arg1:string):Promise<void>;

export function GetDashboardSummary():Promise<main.DashboardSummaryOutput>;

export function GetGoalDetails(arg1:string):Promise<main.GoalOutput>;

export function GetKPIProgress(arg1:string):Promise<main.KPIProgressOutput>;

export function ImportKPIsFromSheet():Promise<main.ImportResultOutput>;

export function ListGoals():Promise<Array<main.GoalOutput>>;

export function ListInitiatives():Promise<Array<main.InitiativeOutput>>;

export function ListInitiativesByGoal(arg1:string):Promise<Array<main.InitiativeOutput>>;

export function ListKPIHistory(arg1:string):Promise<Array<main.KPIEntryOutput>>;

export function ListKPIs():Promise<Array<main.KPIOutput>>;

export function ListKPIsByGoal(arg1:string):Promise<Array<main.KPIOutput>>;

export function ListSnapshots():Promise<Array<main.SnapshotOutput>>;

export function RegisterKPIEntry(arg1:main.RegisterKPIEntryInput):Promise<main.KPIEntryOutput>;

export function SetKPISuccessor(arg1:string,arg2:string):Promise<void>;

export function UpdateGoal(arg1:string,arg2:main.UpdateGoalInput):Promise<main.GoalOutput>;

export function UpdateInitiative(arg1:string,arg2:main.UpdateInitiativeInput):Promise<main.InitiativeOutput>;

export function UpdateKPI(arg1:string,arg2:main.UpdateKPIInput):Promise<main.KPIOutput>;

export function UpdateKPIEntry(arg1:string,arg2:main.UpdateKPIEntryInput):Promise<main.KPIEntryOutput>;
