// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ArchiveGoal(arg1) {
  return window['go']['main']['App']['ArchiveGoal'](arg1);
}

export function ArchiveInitiative(arg1) {
  return window['go']['main']['App']['ArchiveInitiative'](arg1);
}

export function ArchiveKPI(arg1) {
  return window['go']['main']['App']['ArchiveKPI'](arg1);
}

export function CreateGoal(arg1) {
  return window['go']['main']['App']['CreateGoal'](arg1);
}

export function CreateInitiative(arg1) {
  return window['go']['main']['App']['CreateInitiative'](arg1);
}

export function CreateKPI(arg1) {
  return window['go']['main']['App']['CreateKPI'](arg1);
}

export function DeleteKPIEntry(arg1) {
  return window['go']['main']['App']['DeleteKPIEntry'](arg1);
}

export function GetDashboardSummary() {
  return window['go']['main']['App']['GetDashboardSummary']();
}

export function GetGoalDetails(arg1) {
  return window['go']['main']['App']['GetGoalDetails'](arg1);
}

export function GetKPIProgress(arg1) {
  return window['go']['main']['App']['GetKPIProgress'](arg1);
}

export function ImportKPIsFromSheet() {
  return window['go']['main']['App']['ImportKPIsFromSheet']();
}

export function ListGoals() {
  return window['go']['main']['App']['ListGoals']();
}

export function ListInitiatives() {
  return window['go']['main']['App']['ListInitiatives']();
}

export function ListInitiativesByGoal(arg1) {
  return window['go']['main']['App']['ListInitiativesByGoal'](arg1);
}

export function ListKPIHistory(arg1) {
  return window['go']['main']['App']['ListKPIHistory'](arg1);
}

export function ListKPIs() {
  return window['go']['main']['App']['ListKPIs']();
}

export function ListKPIsByGoal(arg1) {
  return window['go']['main']['App']['ListKPIsByGoal'](arg1);
}

export function RegisterKPIEntry(arg1) {
  return window['go']['main']['App']['RegisterKPIEntry'](arg1);
}

export function UpdateGoal(arg1, arg2) {
  return window['go']['main']['App']['UpdateGoal'](arg1, arg2);
}

export function UpdateInitiative(arg1, arg2) {
  return window['go']['main']['App']['UpdateInitiative'](arg1, arg2);
}

export function UpdateKPI(arg1, arg2) {
  return window['go']['main']['App']['UpdateKPI'](arg1, arg2);
}

export function UpdateKPIEntry(arg1, arg2) {
  return window['go']['main']['App']['UpdateKPIEntry'](arg1, arg2);
}
